import { Router } from "express";
import timerRoutes from "./timeTracking";
import superAdminRoutes from "./superAdmin";
import superDebugRoutes from "./superDebug";
import superChatRoutes from "./superChat";
import chatDebugRoutes from "./chatDebug";
import tenantOnboardingRoutes from "./tenantOnboarding";
import tenantBillingRoutes from "./tenantBilling";
import tenancyHealthRoutes from "./tenancyHealth";
import projectsDashboardRoutes from "./projectsDashboard";
import workloadReportsRoutes from "./workloadReports";
import uploadRoutes from "./uploads";
import emailOutboxRoutes from "./emailOutbox";
import systemStatusRoutes from "./systemStatus";
import systemIntegrationsRoutes from "./systemIntegrations";
import chatRoutes from "./chat";
import chatRetentionRoutes from "./chatRetention";
import presenceRoutes from "./presence";
import aiRoutes from "./ai";
import featuresRoutes from "../features";
import superSystemStatusRouter from "./super/systemStatus.router";
import superIntegrationsRouter from "./super/integrations.router";
import superChatExportRouter from "./super/chatExport.router";
import { searchRouter } from "./modules/search/search.router";
import tasksRouter from "./tasks.router";
import timeTrackingRouter from "./timeTracking.router";
import clientsRouter from "./clients.router";
import projectsRouter from "./projects.router";
import usersRouter from "./users.router";

const router = Router();

router.use(usersRouter);
router.use(projectsRouter);
router.use(clientsRouter);
router.use(timeTrackingRouter);
router.use(tasksRouter);
router.use(searchRouter);
router.use(featuresRoutes);
router.use("/timer", timerRoutes);
router.use("/v1/super", superAdminRoutes);
router.use("/v1/super", superSystemStatusRouter);
router.use("/v1/super", superIntegrationsRouter);
router.use("/v1/super/chat", superChatExportRouter);
router.use("/v1/super/debug", superDebugRoutes);
router.use("/v1/super/debug/chat", chatDebugRoutes);
router.use("/v1/super/chat", superChatRoutes);
router.use("/v1/super/status", systemStatusRoutes);
router.use("/v1/system", systemIntegrationsRoutes);
router.use("/v1/tenant", tenantOnboardingRoutes);
router.use("/v1/tenant", tenantBillingRoutes);
router.use("/v1", projectsDashboardRoutes);
router.use("/v1", workloadReportsRoutes);
router.use("/v1/uploads", uploadRoutes);
router.use("/v1", emailOutboxRoutes);
router.use("/v1/chat", chatRoutes);
router.use("/v1", chatRetentionRoutes);
router.use("/v1/presence", presenceRoutes);
router.use("/v1/ai", aiRoutes);
router.use(tenancyHealthRoutes);

export default router;
